FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install screen tmux htop nano python3-pip apt-utils iputils-ping \
					   openssh-server pigz software-properties-common openjdk-8-jdk git curl wget

RUN groupadd -r -g {{ gid }} minecraft && useradd -u {{ uid }} -r -m -g minecraft minecraft

VOLUME ["/minecraft"]
